import 'dotenv/config'; import jwt from 'jsonwebtoken'; import express from 'express'; import cors from 'cors'; import mongoose from 'mongoose'; import argon2 from 'argon2'; import {createServer} from 'node:http'; import {Server} from 'socket.io'; import {User,Conversation,Message,SecurityEvent} from './models.js'; import {tokenFor,requireAuth} from './auth.js';
const app=express(), http=createServer(app); const corsOptions={origin:true,credentials:false}; const io=new Server(http,{cors:{...corsOptions,methods:['GET','POST']}}); app.use(cors(corsOptions)); app.use(express.json({limit:'15mb'}));
const event=async(actor,type,detail='')=>SecurityEvent.create({actor,type,detail}).catch(()=>{}); const safe=u=>({_id:u._id,username:u.username,email:u.email,publicKey:u.publicKey});
app.post('/api/auth/register',async(req,res)=>{try{let {username,email,password,publicKey,privateKeyBackup}=req.body; username=(username||'').trim();email=(email||'').toLowerCase().trim(); if(!/^[a-z0-9_]{3,30}$/i.test(username)||!/^\S+@\S+\.\S+$/.test(email)||!password||password.length<8||!publicKey||!privateKeyBackup)return res.status(400).json({error:'Valid username, email, 8+ character password and public key required'}); const u=await User.create({username,email,passwordHash:await argon2.hash(password,{type:argon2.argon2id}),publicKey,encryptedPrivateKey:privateKeyBackup}); await event(u._id,'REGISTERED');res.status(201).json({token:tokenFor(u),user:safe(u)});}catch(e){res.status(e.code===11000?409:500).json({error:e.code===11000?'Username or email already exists':'Registration failed'});}});
app.post('/api/auth/key-backup',requireAuth,async(req,res)=>{const backup=req.body?.privateKeyBackup;if(!backup?.salt||!backup?.iv||!backup?.cipher)return res.status(400).json({error:'Invalid encrypted key backup'});await User.findByIdAndUpdate(req.user.id,{encryptedPrivateKey:backup});res.json({ok:true});});
app.post('/api/auth/login',async(req,res)=>{const id=(req.body.identity||'').toLowerCase(),u=await User.findOne({$or:[{email:id},{username:req.body.identity}]});if(!u||!await argon2.verify(u.passwordHash,req.body.password||'')){await event(null,'FAILED_LOGIN',id);return res.status(401).json({error:'Invalid credentials'});}await event(u._id,'LOGIN');res.json({token:tokenFor(u),user:safe(u),privateKeyBackup:u.encryptedPrivateKey});});
app.get('/api/users',requireAuth,async(req,res)=>{const q=(req.query.q||'').trim();const users=await User.find({_id:{$ne:req.user.id},$or:[{username:{$regex:q,$options:'i'}},{email:{$regex:q,$options:'i'}}]}).limit(15);res.json(users.map(safe));});
app.get('/api/conversations',requireAuth,async(req,res)=>{const rows=await Conversation.find({members:req.user.id}).populate('members','username email publicKey').sort({lastMessageAt:-1});res.json(rows);});
app.post('/api/conversations',requireAuth,async(req,res)=>{if(req.body.userId===req.user.id)return res.status(400).json({error:'Cannot chat with yourself'});const other=await User.findById(req.body.userId);if(!other)return res.status(404).json({error:'User not found'});let c=await Conversation.findOne({members:{$all:[req.user.id,other._id],$size:2}});if(!c)c=await Conversation.create({members:[req.user.id,other._id]});res.json(await c.populate('members','username email publicKey'));});
const member=async(c,id)=>!!await Conversation.exists({_id:c,members:id});
const clientMessage=m=>{const x=m.toObject?m.toObject():m;return {...x,_id:String(x._id),conversation:String(x.conversation),sender:String(x.sender),deletedFor:(x.deletedFor||[]).map(String)};};
const persistEncryptedMessage=async(payload,userId)=>{if(!await member(payload.conversation,userId))throw Error('Conversation access denied');if(!payload?.encrypted?.cipher||!payload?.encrypted?.iv||!payload?.wrappedKeys)throw Error('Invalid encrypted message payload');const m=await Message.create({conversation:payload.conversation,sender:userId,kind:payload.kind,encrypted:payload.encrypted,wrappedKeys:payload.wrappedKeys,metadata:payload.metadata||{}});await Conversation.findByIdAndUpdate(payload.conversation,{lastMessageAt:new Date});const c=await Conversation.findById(payload.conversation);const outgoing=clientMessage(m);c.members.filter(x=>x.toString()!==userId).forEach(x=>io.to(`user:${x}`).emit('secure-message',outgoing));return outgoing;};app.get('/api/conversations/:id/messages',requireAuth,async(req,res)=>{if(!await member(req.params.id,req.user.id)){await event(req.user.id,'UNAUTHORIZED_CONVERSATION',req.params.id);return res.status(403).json({error:'Conversation access denied'});}res.json((await Message.find({conversation:req.params.id,deletedFor:{$ne:req.user.id}}).sort({sentAt:1})).map(clientMessage));});
app.post('/api/conversations/:id/messages',requireAuth,async(req,res)=>{try{if(req.body.conversation!==req.params.id)return res.status(400).json({error:'Conversation mismatch'});res.status(201).json(await persistEncryptedMessage(req.body,req.user.id));}catch(e){if(e.message==='Conversation access denied'){await event(req.user.id,'UNAUTHORIZED_CONVERSATION',req.params.id);return res.status(403).json({error:e.message});}res.status(400).json({error:e.message});}});
app.delete('/api/messages/:id',requireAuth,async(req,res)=>{const m=await Message.findById(req.params.id);if(!m)return res.status(404).json({error:'Message not found'});if(!await member(m.conversation,req.user.id))return res.status(403).json({error:'Conversation access denied'});const everyone=req.query.everyone==='true';if(everyone){if(String(m.sender)!==req.user.id)return res.status(403).json({error:'Only the sender can delete for everyone'});m.deletedForEveryone=true;m.encrypted={};m.wrappedKeys={};m.metadata={deleted:true};await m.save();const c=await Conversation.findById(m.conversation);c.members.forEach(x=>io.to(`user:${x}`).emit('message-deleted',{id:String(m._id),conversation:String(m.conversation),everyone:true}));}else{if(!m.deletedFor.some(x=>String(x)===req.user.id)){m.deletedFor.push(req.user.id);await m.save();}io.to(`user:${req.user.id}`).emit('message-deleted',{id:String(m._id),conversation:String(m.conversation),everyone:false});}res.json({ok:true,everyone});});app.get('/api/events',requireAuth,async(req,res)=>res.json(await SecurityEvent.find({$or:[{actor:req.user.id},{actor:null}]}).sort({createdAt:-1}).limit(50)));
io.use((socket,next)=>{try{socket.user=jwt.verify(socket.handshake.auth.token,process.env.JWT_SECRET || 'development-only-change-me');next();}catch{next(new Error('unauthorized'));}}); io.on('connection',s=>{s.join(`user:${s.user.id}`);s.on('secure-message',async(payload,ack)=>{try{if(!await member(payload.conversation,s.user.id))throw Error('Conversation access denied');const m=await Message.create({conversation:payload.conversation,sender:s.user.id,kind:payload.kind,encrypted:payload.encrypted,wrappedKeys:payload.wrappedKeys,metadata:payload.metadata||{}});await Conversation.findByIdAndUpdate(payload.conversation,{lastMessageAt:new Date});const c=await Conversation.findById(payload.conversation);c.members.filter(x=>x.toString()!==s.user.id).forEach(x=>io.to(`user:${x}`).emit('secure-message',m));ack?.({ok:true,message:m});}catch(e){ack?.({ok:false,error:e.message});}});});
mongoose.connect(process.env.MONGODB_URI||'mongodb://127.0.0.1:27017/securex').then(()=>http.listen(process.env.PORT||5000,'0.0.0.0',()=>console.log('SecureX API on 0.0.0.0:'+ (process.env.PORT||5000)))).catch(e=>{console.error('MongoDB connection failed:',e.message);process.exit(1)});






