const enc=new TextEncoder(), dec=new TextDecoder(); export const b64=b=>{const bytes=new Uint8Array(b);let binary='';for(let offset=0;offset<bytes.length;offset+=0x8000)binary+=String.fromCharCode(...bytes.subarray(offset,offset+0x8000));return btoa(binary);}; export const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const pem=(label,b)=>`-----BEGIN ${label}-----\n${b.match(/.{1,64}/g).join('\n')}\n-----END ${label}-----`; const unpem=p=>p.replace(/-----(BEGIN|END) [^-]+-----|\s/g,'');
async function passwordKey(password,salt){const base=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:210000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
export async function createIdentity(id,password){const pair=await crypto.subtle.generateKey({name:'RSA-OAEP',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['encrypt','decrypt']);const pub=b64(await crypto.subtle.exportKey('spki',pair.publicKey)),priv=await crypto.subtle.exportKey('pkcs8',pair.privateKey),salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await passwordKey(password,salt),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,priv);const backup={salt:b64(salt),iv:b64(iv),cipher:b64(cipher)};localStorage.setItem('sx-key-'+id,JSON.stringify(backup));return {publicKey:pem('PUBLIC KEY',pub),backup};}
export async function loadPrivate(id,password,backup){let x=JSON.parse(localStorage.getItem('sx-key-'+id));if(!x&&backup){x=backup;localStorage.setItem('sx-key-'+id,JSON.stringify(x));}if(!x)throw Error('This browser does not hold your protected private key. Register/login from the original browser.');const raw=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(x.iv)},await passwordKey(password,unb64(x.salt)),unb64(x.cipher));return crypto.subtle.importKey('pkcs8',raw,{name:'RSA-OAEP',hash:'SHA-256'},false,['decrypt']);}
export async function encryptPayload(data, recipients){const key=await crypto.subtle.generateKey({name:'AES-GCM',length:256},true,['encrypt','decrypt']),iv=crypto.getRandomValues(new Uint8Array(12)),raw=new Uint8Array(await crypto.subtle.exportKey('raw',key)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,data),wrapped={};for(const r of recipients){const pub=await crypto.subtle.importKey('spki',unb64(unpem(r.publicKey)),{name:'RSA-OAEP',hash:'SHA-256'},false,['encrypt']);wrapped[r._id]=b64(await crypto.subtle.encrypt({name:'RSA-OAEP'},pub,raw));}return {encrypted:{cipher:b64(cipher),iv:b64(iv)},wrappedKeys:wrapped};}
export async function decryptPayload(msg,privateKey,id){const raw=await crypto.subtle.decrypt({name:'RSA-OAEP'},privateKey,unb64(msg.wrappedKeys[id]));const key=await crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['decrypt']);return crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(msg.encrypted.iv)},key,unb64(msg.encrypted.cipher));}
export async function digest(text){return b64(await crypto.subtle.digest('SHA-256',enc.encode(text)));} export async function hashBytes(data){return b64(await crypto.subtle.digest('SHA-256',data));} export async function signBytes(data){const pair=await crypto.subtle.generateKey({name:'RSA-PSS',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']),t=performance.now(),signature=await crypto.subtle.sign({name:'RSA-PSS',saltLength:32},pair.privateKey,data),ms=performance.now()-t;return {signature:b64(signature),publicKey:b64(await crypto.subtle.exportKey('spki',pair.publicKey)),ms};} export async function verifyBytes(data,signature,publicKey){const key=await crypto.subtle.importKey('spki',unb64(publicKey),{name:'RSA-PSS',hash:'SHA-256'},false,['verify']);return crypto.subtle.verify({name:'RSA-PSS',saltLength:32},key,unb64(signature),data);} export {enc,dec};




